### ISSUE TITLE
output/Konsole doesn't have light and dark schemes.

### ISSUE THREAD

**Issue by stephenlam** [atelierbram/syntax-highlighting#3]
I'm trying to use atelier cave light for Konsole on KDE but I can't find it. The other terminal emulators have both a light and dark scheme for each color scheme, but Konsole only has a single scheme.

**Comment by atelierbram** [comment]
Indeed, I was just checking the original repo for base16-builder (_were I got the templates from_), but over there as well there is only one [colorscheme.erb](https://github.com/chriskempson/base16-builder/blob/master/templates/konsole/colorscheme.erb) where it should be `light-colorscheme.erb` and `dark-colorscheme.erb`, so yes this is an oversight or at least an omission. 

How I would go about fixing this: 

- make a copy of `colorscheme.erb` and rename those to `dark.colorscheme.erb` and `light.colorscheme.erb`
- leave `dark-colorscheme.erb` alone, but start to reverse-engineer the color variables for `light-colorscheme.erb` with [this light variation of solarized colorscheme for Konsole on KDE](https://github.com/phiggins/konsole-colors-solarized/blob/master/Solarized%20Light.colorscheme) used as a reference.
- regenerate the output
